### ISSUE TITLE
Move JWT_SECRET for serverfinder to secret

### ISSUE THREAD

**Issue by WilSimpson** [ShatteredRealms/Documentation#2]
Example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
```
